# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('editable', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dl_color',
            },
        ),
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('rgb', models.CharField(max_length=16)),
                ('position', models.FloatField(default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dl_color_group',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('position', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dl_size',
            },
        ),
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField(default=None, null=True)),
                ('editable', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=32)),
                ('position', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'dl_size_group',
            },
        ),
        migrations.AddField(
            model_name='size',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='commodity_management.SizeGroup'),
        ),
        migrations.AddField(
            model_name='color',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='commodity_management.ColorGroup'),
        ),
    ]
