# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_management', '0002_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='size',
        ),
        migrations.AddField(
            model_name='sku',
            name='sizes',
            field=models.CharField(default=datetime.datetime(2017, 9, 18, 2, 11, 7, 427373, tzinfo=utc), max_length=32),
            preserve_default=False,
        ),
    ]
